# https://github.com/realm/SwiftLint#configuration
# https://realm.github.io/SwiftLint/rule-directory.html

identifier_name:
  allowed_symbols:
    - _
  excluded:
    - id
    - by
line_length:
  ignores_urls: true
